### ISSUE TITLE
Process starred playlist

### ISSUE THREAD

**Issue by sunnym80** [JMPerez/spotify-dedup#3]
Hi,
When I run dedup, it doesn't list all the playlists I have so I'm not sure if it actually goes through all of them. Please take a look at the following screenshots where it has all the playlists I'm following and which ones dedup used.
![spotify_screenshot](https://cloud.githubusercontent.com/assets/10335607/5566084/0a0f066c-8ee6-11e4-9eb4-82e27a5a47ea.jpg)
![dedup_screenshot](https://cloud.githubusercontent.com/assets/10335607/5566085/0c7388e2-8ee6-11e4-82c8-20aaf605c22f.jpg)

**Comment by sunnym80** [comment]
Hi,
Is the starred playlist something that I own?

Thanks!

**Comment by JMPerez** [comment]
The starred playlist is not publicly supported in the Spotify Web API (see https://github.com/thelinmichael/spotify-web-api-java/pull/10#issuecomment-62012388) but I will try to add it to the lists of playlists to be processed.

**Comment by JMPerez** [comment]
It turns out the starred playlist can be fetched and it is possible to find duplicates in it. However, it is not possible to delete them due to the lack of support for an endpoint like

DELETE https://api.spotify.com/v1/users/_username_/starred/tracks 

in the Spotify Web API. Such a request returns 404.
Unless this is supported in the Web API, the tool won't be able to delete them.

**Comment by sunnym80** [comment]
It would be great to atleast see the dups so they can be deleted manually. What do you think? Is that possible to do?

Thanks!

**Comment by JMPerez** [comment]
Yes, I've done that. It will tell you the duplicates in the Starred playlist and will suggest you to delete them manually.

**Comment by sunnym80** [comment]
Great, thank you very much!!
