### ISSUE TITLE
Process collaborative playlists

### ISSUE THREAD

**Issue by ColtsBR** [JMPerez/spotify-dedup#4]
I have a few collaborative playlists (of which I am the original owner/creator) that spotify-dedup doesn't see/process.

**Comment by JMPerez** [comment]
Unfortunately, modifying a collaborative playlist is an operation that is not supported by the Spotify Web API (see [scopes](https://developer.spotify.com/web-api/using-scopes/)). Since reading is possible, I will implement duplicates-checking and will show a message, encouraging to delete them from a Spotify client.

This is similar to how starred playlists work.
