### ISSUE TITLE
Remove lastly added instead of last in the list

### ISSUE THREAD

**Issue by stephanebruckert** [JMPerez/spotify-dedup#78]
This line https://github.com/JMPerez/spotify-dedup/blob/43b884521341264b8d508d3f8f852c4b0d18bb68/app/scripts/deduplicator.js#L95 currently makes it so that it deletes the last-in-the-list duplicates:

> Artist - Track (added 5 days ago)
> ~Artist - Track (added 6 days ago)~

Since some playlists are sorted by added date descending, it should delete the most recent duplicates to keep the original addition:

> ~Artist - Track (added 5 days ago)~
> Artist - Track (added 6 days ago)

**Comment by JMPerez** [comment]
Since tracks are added at the end of the playlist by default I’d rather
remove the last one.

In any case it doesn’t really matter since the goal is to remove every
appearance except for one.

**Comment by stephanebruckert** [comment]
Sorry I should have mentioned that this would not change the previous behaviour. Both can happen:

- If tracks are added ASC (default): delete the last one as it is currently the case 👍 
- If tracks are added DESC (using `position=0` from the API): temporarily sort by added date and delete the last one -> it will delete what appears to be the first 👍

That would be really helpful in my case because I tend to "value" older additions.

**Comment by JMPerez** [comment]
Since they are duplicate tracks, the tool assumes it can delete any of those. In order to simplify the logic it removes the last ones so it doesn't need to recalculate the indexes of the rest of potential duplicates.
I try to keep the tool as simple as possible and setting which one to delete is out of the scope.

**Comment by Reiszecke** [comment]
Just digging this out for reference. Spend a fair bit of time to compare what the tool actually does because I was confused by Stephane's explanation:

Unless you deliberately add tracks to the top of the playlists (default behavior for Spotify and most other scripts is putting additions at the bottom) the script deletes the most recent additions. So whenever a song has been added for the first time it will show the original date of when it was first added as long as you add your tracks "normally". This is what I initially wanted and I'm happy it does that
